### ISSUE TITLE
Save more than one set of credentials?

### ISSUE THREAD

**Issue by Elektrus** [jsoctocat/BDO-Launcher#16]
I assume that would mean creating a new settings.json for each username so probably a decent amount of work for something that's going to be used only by a few people, but I thought I'd ask.
How I imagine it: [https://i.imgur.com/Izp9D0t.png](https://i.imgur.com/Izp9D0t.png)

Alternatively, I was thinking of a command-line argument for username and password, kinda like [Steam allows to do so](https://help.steampowered.com/en/faqs/view/0188-6BB7-D467-08E1).

**Comment by jsoctocat** [comment]
I will take a look it at over the weekend, do you just want to save the credentials or also the settings per user.

**Comment by Elektrus** [comment]
Oh, I haven't even considered that the OTP is gonna get in the way if the other account isn't using it.
To be honest I'm happy as long as I don't have to copypaste email and password every time, but if you feel like doing some extra work then I would say settings per user sound lovely.

**Comment by jsoctocat** [comment]
I won't be working on this for a while, since this isn't a major bug and I am too busy at the moment.

fastest way to get it to work is pull the source, change saved/load config file name to something else and then compile, do this as many times as the accounts you have.

if you want to nice, you can implement a combo box in place where the current username text box is and save/load the whole thing into an array before writing it to the config file.

or if you want it even better you can redo the UI and add in a new way to select/save users.
