### ISSUE TITLE
(Feature Request) Auto-update or update notification

### ISSUE THREAD

**Issue by moeffju** [jsoctocat/BDO-Launcher#3]
Again, thank you for your work and the quick responses. Much appreciated! I have one more suggestion/feature request: Having a built-in updating function or update notification would be great. I have about 5 of the release files in my download folder and I keep going the Right-click Shortcut -> Properties -> Open File Location, drag & drop from zip file route.

There are some ready-made updaters for .NET like https://github.com/ravibpatel/AutoUpdater.NET (and there may be ones that are easier to integrate with GitHub) - if the launcher could auto-update in place, that would make my life even easier :)

**Comment by jsoctocat** [comment]
I am currently working on another project, so no ETA on this feature request.

**Comment by jsoctocat** [comment]
version 1.1.0c should be the last version needed, it's basically the same as the official launcher at this point since both are using the same framework (except this launcher will only load the bare minimum to start the game, none of the tracking from the official launcher)

if this launcher does break again in the future, I will consider adding an auto-update feature, but for now, the auto-update feature is being postponed indefinitely.

**Comment by moeffju** [comment]
That's also a great solution 😊On Apr 12, 2021 10:29, jsoctocat ***@***.***> wrote:
version 1.1.0c should be the last version needed, it's basically the same as the official launcher at this point since both are using the same framework (except this launcher will only load the bare minimum to start the game, none of the tracking from the official launcher)
if this launcher does break again in the future, I will consider adding an auto-update feature, but for now, the auto-update feature is being postponed indefinitely.
